# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_url', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'verbose_name': 'Статья',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('base_url', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Источники статей',
                'verbose_name': 'Источник статей',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Source'),
        ),
    ]
